### ISSUE TITLE
Missing packages for Yosys when arch is armv71

### ISSUE THREAD

**Issue by rodrigomelo9** [hdl/Termux-packages#1]
To compile Yosys in my armv71 (Moto G6, Android 9), I needed `pkg install tcl python`.

If you are sure that not needed by aarch64 and you like the idea, I can compare the output of `uname -m` with `armv71` to install the additional packages. Let me know.

**Comment by umarcor** [comment]
I think it's ok to add them into `base.sh` by default. We'll take care of more granular dependency definition when proper packages are created.
